### ISSUE TITLE
ASG / Horizontal Scaling is not appropriate as the Validator maintains a single keypair

### ISSUE THREAD

**Issue by rob-casper** [nclouds/casper-infrastructure#1]
https://github.com/nclouds/casper-infrastructure/blob/ab6108b64862dedf5068d307d29d4fd8251ab789/templates/casper-node.yml#L269

**Comment by ronaldour** [comment]
As we mentioned in our last meeting the AutoScaling group is configured  with a desired, minimum and maximum count of 1. This means that the ASG is not going to scale, it's only used to add resiliency to the node. If the node goes down for any reason the ASG will try to recreate it automatically.

**Comment by ronaldour** [comment]
The templates were changed to create a single instance instead of the ASG
